// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUrsY0fxEWwEvmF3xKaIFNRS1nHzCnVas',
    appId: '1:456791291056:web:7533105cbe961504d6f775',
    messagingSenderId: '456791291056',
    projectId: 'finstagram-1be12',
    authDomain: 'finstagram-1be12.firebaseapp.com',
    storageBucket: 'finstagram-1be12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHCbkeFjQ_JmJOozGA6aVU1fU8TlZyAfM',
    appId: '1:456791291056:android:135ac1e974154cfdd6f775',
    messagingSenderId: '456791291056',
    projectId: 'finstagram-1be12',
    storageBucket: 'finstagram-1be12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkYhGHlxi_d15TfBmFviOFVyqVxDctfs8',
    appId: '1:456791291056:ios:83375682ff4dfd69d6f775',
    messagingSenderId: '456791291056',
    projectId: 'finstagram-1be12',
    storageBucket: 'finstagram-1be12.appspot.com',
    iosClientId: '456791291056-cdqjhsrg45u29culcasnlof258e6o6rf.apps.googleusercontent.com',
    iosBundleId: 'com.qpthedev.finstagram',
  );
}
